### ISSUE TITLE
clockotherwise and mirroring photo

### ISSUE THREAD

**Issue by Shaverdoff** [jomjol/water-meter-system-complete#64]
Good day!  i was installed docker version with that compose

```
version: "3"

services:
    mlcnt:
      restart: always
      image: jomjol/wasserzaehler:latest
      ports:
        - 3000:3000
      volumes:
        - "/opt:/config"
        - "/opt:/log"
```
also try to run single docker at 
`docker run -p 3000:3000 --mount type=bind,source=/opt,target=/config --mount type=bind,source=/opt,target=/log jomjol/wasserzaehler:latest
`
no luck... picture is the same crumpled 

whold you be i pice of kind explain why this behavior still appear... 
![Снимок экрана 2021-04-02 в 03 30 17](https://user-images.githubusercontent.com/43804710/113364126-c0c34480-9363-11eb-9a18-99cc980ddb53.png)
 
screen that was make as example correctly
![counter](https://user-images.githubusercontent.com/43804710/113364185-e9e3d500-9363-11eb-823d-fa0430711fa8.png)

why server crumpled and mirroring it?
where in config is parametrs to normalize photo?
